<a href="https://colab.research.google.com/github/neerukondaramalakshmi2005-dotcom/EDA-HMS/blob/main/AUTOMATIC_TOOLS_HMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TOOLS FOR AUTOMATIC EDA OPERATIONS
============================

 1. ! pip install dtale
 2. ! pip install ydata-profiling
 3. ! pip install  autoviz.AutoViz_class
 4. ! pip install

| Tool                | Main Purpose                  | What it gives                                                    |
| ------------------- | ----------------------------- | ---------------------------------------------------------------- |
| **D-Tale**          | Interactive data exploration  | Data table, statistics, charts, missing values                   |
| **YData Profiling** | Automatic data profiling      | Complete EDA report, correlations, missing values, distributions |
| **AutoViz**         | Automatic visualization       | Automatically generates useful graphs                            |
| **Sweetviz**        | Dataset analysis & comparison | Visual EDA report, distributions, correlations, comparisons      |

In [6]:
import pandas as pd

A = pd.read_csv("/content/appointments.csv")
B = pd.read_csv("/content/billing.csv")
D = pd.read_csv("/content/doctors.csv")
P = pd.read_csv("/content/patients.csv")
T = pd.read_csv("/content/treatments.csv")
print(A)
print(B)
print(D)
print(P)
print(T)

    appointment_id patient_id doctor_id appointment_date appointment_time  \
0             A001       P034      D009       2023-08-09         15:15:00
1             A002       P032      D004       2023-06-09         14:30:00
2             A003       P048      D004       2023-06-28          8:00:00
3             A004       P025      D006       2023-09-01          9:15:00
4             A005       P040      D003       2023-07-06         12:45:00
..             ...        ...       ...              ...              ...
195           A196       P045      D006       2023-10-26          9:45:00
196           A197       P001      D005       2023-04-01         13:30:00
197           A198       P022      D006       2023-05-15          8:30:00
198           A199       P017      D001       2023-05-01         12:45:00
199           A200       P007      D005       2023-12-30         10:15:00

    reason_for_visit     status
0            Therapy  Scheduled
1            Therapy    No-show
2       Consultation  Cancelled
3       Consultation  Cancelled
4          Emergency    No-show
..               ...        ...
195          Checkup  Cancelled
196        Emergency    No-show
197          Therapy    No-show
198        Follow-up  Completed
199     Consultation  Cancelled

[200 rows x 7 columns]
    bill_id patient_id treatment_id   bill_date   amount payment_method  \
0      B001       P034         T001  2023-08-09  3941.97      Insurance
1      B002       P032         T002  2023-06-09  4158.44      Insurance
2      B003       P048         T003  2023-06-28  3731.55      Insurance
3      B004       P025         T004  2023-09-01  4799.86      Insurance
4      B005       P040         T005  2023-07-06   582.05    Credit Card
..      ...        ...          ...         ...      ...            ...
195    B196       P045         T196  2023-10-26  2477.80           Cash
196    B197       P001         T197  2023-04-01   975.49           Cash
197    B198       P022         T198  2023-05-15  3383.72           Cash
198    B199       P017         T199  2023-05-01  1472.17    Credit Card
199    B200       P007         T200  2023-12-30  3288.15      Insurance

    payment_status
0          Pending
1             Paid
2             Paid
3           Failed
4          Pending
..             ...
195        Pending
196        Pending
197         Failed
198           Paid
199           Paid

[200 rows x 7 columns]
  doctor_id first_name last_name specialization  phone_number  \
0      D001      David    Taylor    Dermatology    8322010158
1      D002       Jane     Davis     Pediatrics    9004382050
2      D003       Jane     Smith     Pediatrics    8737740598
3      D004      David     Jones     Pediatrics    6594221991
4      D005      Sarah    Taylor    Dermatology    9118538547
5      D006       Alex     Davis     Pediatrics    6570137231
6      D007     Robert     Davis       Oncology    8217493115
7      D008      Linda     Brown    Dermatology    9069162601
8      D009      Sarah     Smith     Pediatrics    7387087517
9      D010      Linda    Wilson       Oncology    6176383634

   years_experience   hospital_branch                         email
0                17   Westside Clinic  dr.david.taylor@hospital.com
1                24   Eastside Clinic    dr.jane.davis@hospital.com
2                19   Eastside Clinic    dr.jane.smith@hospital.com
3                28  Central Hospital   dr.david.jones@hospital.com
4                26  Central Hospital  dr.sarah.taylor@hospital.com
5                23  Central Hospital    dr.alex.davis@hospital.com
6                26   Westside Clinic  dr.robert.davis@hospital.com
7                 5   Westside Clinic   dr.linda.brown@hospital.com
8                26  Central Hospital   dr.sarah.smith@hospital.com
9                21   Eastside Clinic  dr.linda.wilson@hospital.com
   patient_id first_name last_name gender date_of_birth  contact_number  \
0        P001      David  Williams      F    1955-06-04      6939585183
1        P002      Emily     Smith      F    1984-10-12      8228188767
2        P003      Laura     Jones      M    1977-08-21      8397029847
3        P004    Michael   Johnson      F    1981-02-20      9019443432
4        P005      David    Wilson      M    1960-06-23      7734463155
5        P006      Linda     Jones      M    1963-06-16      7561777264
6        P007       Alex   Johnson      F    1989-06-08      6278710077
7        P008      David     Davis      F    1976-07-05      7090558393
8        P009      Laura     Davis      M    1971-12-11      7060324619
9        P010    Michael    Taylor      M    2001-10-13      7081396733
10       P011      Emily     Jones      F    1966-12-04      8990604070
11       P012      Laura     Davis      F    1991-12-08      8135666049
12       P013      Laura   Johnson      F    1990-03-28      9059178882
13       P014       Alex    Taylor      M    1968-02-27      7292262512
14       P015      Sarah   Johnson      M    1964-05-11      6636028516
15       P016    Michael    Taylor      M    2000-07-22      7223380592
16       P017       Jane     Jones      M    1991-05-01      6158428240
17       P018      Laura    Wilson      M    1979-09-24      7145815738
18       P019      Sarah    Miller      M    1975-05-24      8618058864
19       P020       Jane     Moore      F    2003-06-06      8158989953
20       P021    Michael    Wilson      M    2002-03-01      7765390555
21       P022       John     Brown      M    1955-05-10      6221099573
22       P023      Linda   Johnson      M    1994-02-22      6141951830
23       P024      Sarah     Brown      F    1991-11-04      7196777444
24       P025     Robert    Wilson      M    1966-08-14      7482069727
25       P026       John    Taylor      M    2003-11-28      9900972256
26       P027      Linda     Moore      F    1998-06-29      8724518272
27       P028       Alex     Moore      M    1993-04-13      7028910482
28       P029      David     Smith      M    2005-05-15      8923607677
29       P030      Emily     Moore      M    1964-12-23      6622318721
30       P031     Robert    Miller      M    1987-01-14      8280346676
31       P032       Alex     Moore      M    1981-01-08      8102183595
32       P033    Michael    Wilson      F    1970-02-06      7923214041
33       P034       Alex     Smith      F    1950-01-26      8374657733
34       P035      David    Wilson      F    1993-04-13      7039619487
35       P036    Michael    Wilson      M    1997-12-26      8545613046
36       P037     Robert  Williams      M    1999-02-05      8886800195
37       P038      David     Smith      M    1991-06-25      6347262390
38       P039       Jane    Wilson      F    1950-12-12      9271131338
39       P040      Emily  Williams      M    1972-05-30      7587653815
40       P041     Robert  Williams      M    1951-06-19      7020645498
41       P042       Jane     Smith      F    1954-08-22      7040069008
42       P043      Linda     Brown      M    1980-03-25      9127665406
43       P044     Robert    Taylor      F    1976-03-11      9449458981
44       P045      Linda    Miller      F    1966-04-25      7579616535
45       P046    Michael    Taylor      F    1986-09-01      8019925828
46       P047       Jane     Moore      M    1995-12-13      8715732851
47       P048      Emily    Miller      M    1983-03-24      8720989381
48       P049      David     Moore      M    1972-11-26      7712937941
49       P050      Laura    Wilson      M    1993-12-27      8301134730

         address registration_date insurance_provider insurance_number  \
0    789 Pine Rd        2022-06-23       WellnessCorp        INS840674
1   321 Maple Dr        2022-01-15        PulseSecure        INS354079
2   321 Maple Dr        2022-02-07        PulseSecure        INS650929
3     123 Elm St        2021-03-02        HealthIndia        INS789944
4     123 Elm St        2021-09-29       MedCare Plus        INS788105
5   321 Maple Dr        2022-10-02        HealthIndia        INS613758
6    789 Pine Rd        2021-12-25       MedCare Plus        INS465890
7    456 Oak Ave        2021-05-25       WellnessCorp        INS545101
8   321 Maple Dr        2022-09-18        PulseSecure        INS136631
9     123 Elm St        2022-08-24       WellnessCorp        INS866577
10   789 Pine Rd        2022-09-27       MedCare Plus        INS172991
11  321 Maple Dr        2023-04-27       MedCare Plus        INS104014
12  321 Maple Dr        2021-12-23       WellnessCorp        INS373237
13   789 Pine Rd        2023-12-12       MedCare Plus        INS118070
14  321 Maple Dr        2021-09-25       WellnessCorp        INS922209
15   789 Pine Rd        2021-07-23        PulseSecure        INS156958
16   456 Oak Ave        2022-09-26       WellnessCorp        INS182074
17   789 Pine Rd        2022-09-23        PulseSecure        INS635017
18   789 Pine Rd        2023-06-24       WellnessCorp        INS855073
19   789 Pine Rd        2022-04-03       MedCare Plus        INS276089
20  321 Maple Dr        2022-01-19       WellnessCorp        INS297392
21  321 Maple Dr        2021-05-11       MedCare Plus        INS258823
22   789 Pine Rd        2021-12-27       WellnessCorp        INS730152
23  321 Maple Dr        2021-09-02       WellnessCorp        INS493002
24    123 Elm St        2021-09-09        HealthIndia        INS833429
25    123 Elm St        2021-05-13       MedCare Plus        INS598863
26  321 Maple Dr        2021-08-15        HealthIndia        INS467654
27  321 Maple Dr        2023-05-20       MedCare Plus        INS679036
28   789 Pine Rd        2023-04-19        HealthIndia        INS630089
29   456 Oak Ave        2021-08-07        PulseSecure        INS250262
30  321 Maple Dr        2022-06-28       WellnessCorp        INS542905
31    123 Elm St        2021-10-02       MedCare Plus        INS335362
32   789 Pine Rd        2023-09-06       MedCare Plus        INS544209
33  321 Maple Dr        2023-06-18       WellnessCorp        INS653880
34    123 Elm St        2023-07-09       MedCare Plus        INS897079
35    123 Elm St        2022-10-04       MedCare Plus        INS764076
36   456 Oak Ave        2021-09-30        HealthIndia        INS319963
37   789 Pine Rd        2021-04-19       MedCare Plus        INS580761
38   789 Pine Rd        2021-03-09        PulseSecure        INS348710
39   456 Oak Ave        2021-10-16        PulseSecure        INS320984
40   456 Oak Ave        2022-07-16       WellnessCorp        INS997059
41   789 Pine Rd        2022-03-15       MedCare Plus        INS956748
42   789 Pine Rd        2022-07-18       WellnessCorp        INS882355
43  321 Maple Dr        2023-01-26        PulseSecure        INS364512
44  321 Maple Dr        2021-01-23       MedCare Plus        INS701863
45   456 Oak Ave        2021-07-31       MedCare Plus        INS368799
46  321 Maple Dr        2022-05-20       WellnessCorp        INS337549
47    123 Elm St        2023-06-19        PulseSecure        INS694319
48  321 Maple Dr        2023-06-14       MedCare Plus        INS584299
49  321 Maple Dr        2023-04-28       WellnessCorp        INS712210

                       email
0    david.williams@mail.com
1       emily.smith@mail.com
2       laura.jones@mail.com
3   michael.johnson@mail.com
4      david.wilson@mail.com
5       linda.jones@mail.com
6      alex.johnson@mail.com
7       david.davis@mail.com
8       laura.davis@mail.com
9    michael.taylor@mail.com
10      emily.jones@mail.com
11      laura.davis@mail.com
12    laura.johnson@mail.com
13      alex.taylor@mail.com
14    sarah.johnson@mail.com
15   michael.taylor@mail.com
16       jane.jones@mail.com
17     laura.wilson@mail.com
18     sarah.miller@mail.com
19       jane.moore@mail.com
20   michael.wilson@mail.com
21       john.brown@mail.com
22    linda.johnson@mail.com
23      sarah.brown@mail.com
24    robert.wilson@mail.com
25      john.taylor@mail.com
26      linda.moore@mail.com
27       alex.moore@mail.com
28      david.smith@mail.com
29      emily.moore@mail.com
30    robert.miller@mail.com
31       alex.moore@mail.com
32   michael.wilson@mail.com
33       alex.smith@mail.com
34     david.wilson@mail.com
35   michael.wilson@mail.com
36  robert.williams@mail.com
37      david.smith@mail.com
38      jane.wilson@mail.com
39   emily.williams@mail.com
40  robert.williams@mail.com
41       jane.smith@mail.com
42      linda.brown@mail.com
43    robert.taylor@mail.com
44     linda.miller@mail.com
45   michael.taylor@mail.com
46       jane.moore@mail.com
47     emily.miller@mail.com
48      david.moore@mail.com
49     laura.wilson@mail.com
    treatment_id appointment_id treatment_type         description     cost  \
0           T001           A001   Chemotherapy     Basic screening  3941.97
1           T002           A002            MRI   Advanced protocol  4158.44
2           T003           A003            MRI  Standard procedure  3731.55
3           T004           A004            MRI     Basic screening  4799.86
4           T005           A005            ECG  Standard procedure   582.05
..           ...            ...            ...                 ...      ...
195         T196           A196   Chemotherapy   Advanced protocol  2477.80
196         T197           A197  Physiotherapy  Standard procedure   975.49
197         T198           A198            ECG     Basic screening  3383.72
198         T199           A199   Chemotherapy     Basic screening  1472.17
199         T200           A200          X-Ray     Basic screening  3288.15

    treatment_date
0       2023-08-09
1       2023-06-09
2       2023-06-28
3       2023-09-01
4       2023-07-06
..             ...
195     2023-10-26
196     2023-04-01
197     2023-05-15
198     2023-05-01
199     2023-12-30

[200 rows x 6 columns]

In [10]:
! pip install dtale

Collecting dtale
  Downloading dtale-3.22.0-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: lz4 in /usr/local/lib/python3.13/dist-packages (from dtale) (4.4.5)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in /usr/local/lib/python3.13/dist-packages (from dtale) (4.13.5)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from dtale) (2026.10.23)
Requirement already satisfied: cycler in /usr/local/lib/python3.13/dist-packages (from dtale) (0.12.1)
Collecting dash (from dtale)
  Downloading dash-4.4.1-py3-none-any.whl.metadata (11 kB)
Collecting dash-bootstrap-components (from dtale)
  Downloading dash_bootstrap_components-2.0.4-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: et_xmlfile in /usr/local/lib/python3.13/dist-packages (from dtale) (2.0.0)
Requirement already satisfied: Flask in /usr/local/lib/python3.13/dist-packages (from dtale) (3.1.3)
Collecting Flask-Compress (from dtale)
  Downloading flask_compress-1.26-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: future>=0.14.0 in /usr/local/lib/python3.13/dist-packages (from dtale) (1.0.0)
Requirement already satisfied: itsdangerous in /usr/local/lib/python3.13/dist-packages (from dtale) (2.2.0)
Collecting kaleido (from dtale)
  Downloading kaleido-1.5.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from dtale) (3.10.0)
Requirement already satisfied: missingno in /usr/local/lib/python3.13/dist-packages (from dtale) (0.5.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from dtale) (3.7)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from dtale) (2.1.3)
Requirement already satisfied: openpyxl!=3.2.0b1 in /usr/local/lib/python3.13/dist-packages (from dtale) (3.1.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from dtale) (26.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from dtale) (2.2.3)
Collecting pkginfo (from dtale)
  Downloading pkginfo-2.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from dtale) (5.24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from dtale) (2.32.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from dtale) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from dtale) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (from dtale) (0.13.2)
Collecting squarify (from dtale)
  Downloading squarify-0.4.5-py3-none-any.whl.metadata (750 bytes)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from dtale) (0.15.0)
Collecting strsimpy (from dtale)
  Downloading strsimpy-0.2.1-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from dtale) (1.17.0)
Requirement already satisfied: werkzeug in /usr/local/lib/python3.13/dist-packages (from dtale) (3.1.9)
Requirement already satisfied: xarray in /usr/local/lib/python3.13/dist-packages (from dtale) (2025.12.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (from dtale) (2.0.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4!=4.13.0b2->dtale) (3.0.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4!=4.13.0b2->dtale) (4.16.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (10.1.0)
Collecting retrying (from dash->dtale)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (80.10.2)
Collecting janus>=1.0.0 (from dash->dtale)
  Downloading janus-2.0.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic>=2.10 in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (2.14.1)
Collecting comm (from dash->dtale)
  Downloading comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (8.5.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (3.0.4)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->dtale) (9.1.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.10->dash->dtale) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.10->dash->dtale) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.10->dash->dtale) (0.4.4)
Requirement already satisfied: brotli in /usr/local/lib/python3.13/dist-packages (from Flask-Compress->dtale) (1.2.1)
Collecting backports.zstd (from Flask-Compress->dtale)
  Downloading backports_zstd-1.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata->dash->dtale) (4.1.2)
Collecting choreographer>=1.4.0 (from kaleido->dtale)
  Downloading choreographer-1.4.0-py3-none-any.whl.metadata (5.5 kB)
Collecting logistro>=1.0.8 (from kaleido->dtale)
  Downloading logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.13/dist-packages (from choreographer>=1.4.0->kaleido->dtale) (4.13.5)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.13/dist-packages (from choreographer>=1.4.0->kaleido->dtale) (4.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (1.4.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->dtale) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->dtale) (2026.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->dtale) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->dtale) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->dtale) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtale) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtale) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->dtale) (3.1.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->dtale) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels->dtale) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->dtale) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->dtale) (2.27.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->dtale) (2.5.1)
Downloading dtale-3.22.0-py2.py3-none-any.whl (17.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.4/17.4 MB 92.6 MB/s  0:00:00
Downloading dash-4.4.1-py3-none-any.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 136.5 MB/s  0:00:00
Downloading janus-2.0.0-py3-none-any.whl (12 kB)
Downloading comm-0.2.3-py3-none-any.whl (7.3 kB)
Downloading dash_bootstrap_components-2.0.4-py3-none-any.whl (204 kB)
Downloading flask_compress-1.26-py3-none-any.whl (11 kB)
Downloading backports_zstd-1.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (493 kB)
Downloading kaleido-1.5.0-py3-none-any.whl (55 kB)
Downloading choreographer-1.4.0-py3-none-any.whl (57 kB)
Downloading logistro-2.0.1-py3-none-any.whl (8.6 kB)
Downloading pkginfo-2.0-py3-none-any.whl (16 kB)
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Downloading squarify-0.4.5-py3-none-any.whl (4.1 kB)
Downloading strsimpy-0.2.1-py3-none-any.whl (45 kB)
Installing collected packages: strsimpy, squarify, retrying, pkginfo, logistro, janus, comm, backports.zstd, choreographer, kaleido, Flask-Compress, dash, dash-bootstrap-components, dtale
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/14 [dtale]
Successfully installed Flask-Compress-1.26 backports.zstd-1.8.0 choreographer-1.4.0 comm-0.2.3 dash-4.4.1 dash-bootstrap-components-2.0.4 dtale-3.22.0 janus-2.0.0 kaleido-1.5.0 logistro-2.0.1 pkginfo-2.0 retrying-1.4.2 squarify-0.4.5 strsimpy-0.2.1

In [11]:
import dtale
import pandas as pd

# Open and display interactive D-Tale sheets for the dataframes
dtale.show(A)  # Appointments
dtale.show(B)  # Billing
dtale.show(D)  # Doctors
dtale.show(P)  # Patients
dtale.show(T)  # Treatments

/usr/local/lib/python3.13/dist-packages/kaleido/_sync_server.py:11: UserWarning:



Warning: You have Plotly version 5.24.1, which is not compatible with this version of Kaleido (1.5.0).

This means that static image generation (e.g. `fig.write_image()`) will not work.

Please upgrade Plotly to version 6.1.1 or greater, or downgrade Kaleido to version 0.2.1.

You can however, use the Kaleido API directly which will work with your plotly version. `kaleido.write_fig(...)`, for example. Please see the kaleido documentation.

http://1af2d6e8a2be:40000/dtale/main/5

In [12]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.14.1)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.1.3)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.15.0)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.6.0)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.10.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.5)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.50.1)
Requirement already satisfied: typing-extensions>=4.16.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.10.23)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.2.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.7)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.27.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.5.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.14.1->phik<0.13,>=0.12.5->ydata-profiling) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (682 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 6.3 MB/s  0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 26.2 MB/s  0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [ydata-profiling]
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

In [13]:
from ydata_profiling import ProfileReport

ProfileReport(A, title="Appointments Report")
ProfileReport(B, title="Billing Report")
ProfileReport(D, title="Doctors Report")
ProfileReport(P, title="Patients Report")
ProfileReport(T, title="Treatments Report")

/tmp/ipykernel_1921/1887041609.py:1: DeprecationWarning:


    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]
100%|██████████| 6/6 [00:00<00:00, 37.42it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [18]:
! pip install autoviz

Requirement already satisfied: autoviz in /usr/local/lib/python3.13/dist-packages (0.1.905)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.0.2)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.9.6)
Requirement already satisfied: emoji in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.16.0)
Requirement already satisfied: pyamg in /usr/local/lib/python3.13/dist-packages (from autoviz) (5.3.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.15.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from autoviz) (3.9.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.19.0)
Requirement already satisfied: xgboost<1.7,>=0.82 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.6.2)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.13/dist-packages (from autoviz) (2025.12.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.13/dist-packages (from autoviz) (4.16.0)
Requirement already satisfied: pandas-dq>=1.29 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.29)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.1.3)
Requirement already satisfied: hvplot>=0.9.2 in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.12.2)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.23.2)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.9.4)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.2.3)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.13/dist-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.13.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost<1.7,>=0.82->autoviz) (1.16.3)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (3.8.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (3.2.1)
Requirement already satisfied: narwhals>=2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (2.27.1)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (3.0.6)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (1.4.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (26.3)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2026.9.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (1.5.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (3.3.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->autoviz) (2026.5)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (2.2.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (3.11.2)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (0.6.1)
Requirement already satisfied: nh3 in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (0.3.7)
Requirement already satisfied: panel-material-ui>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (0.16.6)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (4.67.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->autoviz) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->autoviz) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->autoviz) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->autoviz) (3.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->autoviz) (8.5.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk->autoviz) (2025.11.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (2026.10.23)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->autoviz) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels->autoviz) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->autoviz) (2.0.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->autoviz) (2.5.1)

In [26]:
# Note: The wordcloud warning below is normal for non-text/date columns and can be ignored.
!python -m textblob.download_corpora

from autoviz.AutoViz_Class import AutoViz_Class

AV = AutoViz_Class()

AV.AutoViz("/content/appointments.csv", sep=",", depVar="status", dfte=A)
AV.AutoViz("/content/billing.csv", sep=",", depVar="amount", dfte=B)
AV.AutoViz("/content/doctors.csv", sep=",", depVar="specialization", dfte=D)
AV.AutoViz("/content/patients.csv", sep=",", depVar="date_of_birth", dfte=P)
AV.AutoViz("/content/treatments.csv", sep=",", depVar="cost", dfte=T)

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.
Shape of your Data Set loaded: (200, 7)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  4
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  1
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    6 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['appointment_id']

################ Multi_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

No continuous var in data set: drawing categorical distribution plots

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

Could not draw wordcloud plot for appointment_date. We need at least 1 word to plot a word cloud, got 0.
All Plots done
Time to run AutoViz = 2 seconds

 ###################### AUTO VISUALIZATION Completed ########################
Shape of your Data Set loaded: (200, 7)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  3
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  1
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  2
    Number of Columns to Delete =  0
    6 Predictors classified...
        2 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['bill_id', 'treatment_id']

################ Regression problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Could not draw wordcloud plot for bill_date. We need at least 1 word to plot a word cloud, got 0.
All Plots done
Time to run AutoViz = 1 seconds

 ###################### AUTO VISUALIZATION Completed ########################
Shape of your Data Set loaded: (10, 8)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  1
    Number of String-Categorical Columns =  3
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  3
    Number of Columns to Delete =  0
    7 Predictors classified...
        3 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['phone_number', 'doctor_id', 'email']

################ Multi_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

All Plots done
Time to run AutoViz = 1 seconds

 ###################### AUTO VISUALIZATION Completed ########################
Shape of your Data Set loaded: (50, 11)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  5
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  4
    Number of Columns to Delete =  0
    10 Predictors classified...
        4 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['patient_id', 'contact_number', 'registration_date', 'insurance_number']

################ Multi_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

No continuous var in data set: drawing categorical distribution plots
All Plots done
Time to run AutoViz = 1 seconds

 ###################### AUTO VISUALIZATION Completed ########################
Shape of your Data Set loaded: (200, 6)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  2
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  1
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  2
    Number of Columns to Delete =  0
    5 Predictors classified...
        2 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['treatment_id', 'appointment_id']

################ Regression problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Could not draw wordcloud plot for treatment_date. We need at least 1 word to plot a word cloud, got 0.
All Plots done
Time to run AutoViz = 0 seconds

 ###################### AUTO VISUALIZATION Completed ########################

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

    treatment_type     description     treatment_date   cost
0     Chemotherapy     Basic screening   2023-08-09    3941.97
1              MRI   Advanced protocol   2023-06-09    4158.44
2              MRI  Standard procedure   2023-06-28    3731.55
3              MRI     Basic screening   2023-09-01    4799.86
4              ECG  Standard procedure   2023-07-06     582.05
5     Chemotherapy  Standard procedure   2023-06-19    1381.00
6     Chemotherapy   Advanced protocol   2023-04-09     534.03
7    Physiotherapy     Basic screening   2023-05-24    3413.64
8    Physiotherapy  Standard procedure   2023-03-05    4541.14
9    Physiotherapy  Standard procedure   2023-01-13    1595.67
10             MRI     Basic screening   2023-11-12    4671.66
11    Chemotherapy  Standard procedure   2023-05-07     771.20
12             MRI  Standard procedure   2023-08-16    4704.96
13             ECG     Basic screening   2023-05-25    2082.30
14   Physiotherapy     Basic screening   2023-01-15     956.39
15             MRI     Basic screening   2023-06-30    2686.42
16             MRI     Basic screening   2023-07-11    1655.49
17             ECG   Advanced protocol   2023-11-14    1781.93
18           X-Ray     Basic screening   2023-02-06    1882.80
19    Chemotherapy   Advanced protocol   2023-12-05    4113.62
20           X-Ray   Advanced protocol   2023-04-24    2926.23
21   Physiotherapy   Advanced protocol   2023-11-14    1900.88
22             MRI  Standard procedure   2023-05-09    3246.50
23             ECG   Advanced protocol   2023-06-21    3722.68
24             ECG   Advanced protocol   2023-02-25    1726.81
25    Chemotherapy  Standard procedure   2023-03-17    2360.97
26           X-Ray  Standard procedure   2023-11-14    1048.49
27    Chemotherapy  Standard procedure   2023-10-29    1315.17
28             MRI     Basic screening   2023-06-25    3565.03
29    Chemotherapy  Standard procedure   2023-08-29    1316.47
30             ECG  Standard procedure   2023-04-04    2863.24
31             ECG   Advanced protocol   2023-11-06    3690.71
32   Physiotherapy  Standard procedure   2023-09-23     980.95
33   Physiotherapy     Basic screening   2023-06-13    3052.90
34             MRI  Standard procedure   2023-04-18    1654.53
35           X-Ray     Basic screening   2023-01-08    4833.17
36    Chemotherapy  Standard procedure   2023-03-28    2675.96
37             MRI  Standard procedure   2023-02-23    4126.97
38   Physiotherapy  Standard procedure   2023-04-17    2976.02
39    Chemotherapy  Standard procedure   2023-03-27     695.36
40   Physiotherapy     Basic screening   2023-01-01    3349.18
41    Chemotherapy     Basic screening   2023-03-21    4781.32
42           X-Ray   Advanced protocol   2023-03-29    3207.25
43             MRI     Basic screening   2023-09-20    4186.35
44    Chemotherapy  Standard procedure   2023-09-28    4478.93
45             ECG   Advanced protocol   2023-12-20    1526.36
46             ECG   Advanced protocol   2023-05-02    1454.20
47    Chemotherapy   Advanced protocol   2023-01-16    3249.41
48    Chemotherapy  Standard procedure   2023-04-30    2349.63
49    Chemotherapy     Basic screening   2023-08-16    4279.38
50             ECG  Standard procedure   2023-02-04    4550.10
51             ECG   Advanced protocol   2023-07-12    2090.40
52    Chemotherapy  Standard procedure   2023-02-12    1565.92
53   Physiotherapy  Standard procedure   2023-12-16    4012.36
54   Physiotherapy     Basic screening   2023-10-06    1736.63
55           X-Ray     Basic screening   2023-01-02    4201.76
56             MRI   Advanced protocol   2023-04-15    2406.82
57   Physiotherapy  Standard procedure   2023-05-09    3503.97
58             ECG  Standard procedure   2023-03-09     929.91
59   Physiotherapy     Basic screening   2023-11-22    3307.37
60           X-Ray  Standard procedure   2023-01-15    2532.95
61           X-Ray  Standard procedure   2023-06-14    3139.74
62             MRI  Standard procedure   2023-06-29    1256.06
63   Physiotherapy     Basic screening   2023-05-31    3815.93
64             ECG   Advanced protocol   2023-04-24    4382.59
65             ECG   Advanced protocol   2023-05-10    1475.33
66    Chemotherapy  Standard procedure   2023-08-10     930.72
67             ECG   Advanced protocol   2023-03-14     606.37
68             MRI     Basic screening   2023-03-29    3388.87
69             MRI     Basic screening   2023-08-26    3231.92
70             ECG   Advanced protocol   2023-01-26    2960.14
71             ECG   Advanced protocol   2023-06-12    1543.76
72    Chemotherapy  Standard procedure   2023-12-24    2259.08
73             ECG   Advanced protocol   2023-07-23    3175.14
74    Chemotherapy  Standard procedure   2023-05-08    2735.45
75    Chemotherapy  Standard procedure   2023-11-27    4945.03
76             ECG     Basic screening   2023-12-14    1113.98
77           X-Ray     Basic screening   2023-09-17    3628.15
78           X-Ray     Basic screening   2023-12-26    2319.43
79    Chemotherapy     Basic screening   2023-06-26    2426.90
80             ECG   Advanced protocol   2023-01-06    3729.19
81           X-Ray     Basic screening   2023-01-20    3615.96
82             ECG   Advanced protocol   2023-11-07    4960.65
83             ECG     Basic screening   2023-05-31    1077.77
84             ECG   Advanced protocol   2023-02-18     968.49
85   Physiotherapy  Standard procedure   2023-10-29    3759.52
86             ECG   Advanced protocol   2023-10-19    3102.74
87   Physiotherapy   Advanced protocol   2023-05-02    1733.72
88    Chemotherapy     Basic screening   2023-02-14     857.39
89           X-Ray   Advanced protocol   2023-06-01     885.46
90           X-Ray  Standard procedure   2023-06-11    4523.86
91           X-Ray  Standard procedure   2023-01-30    1363.40
92           X-Ray     Basic screening   2023-04-09    1955.17
93           X-Ray  Standard procedure   2023-04-08    1519.95
94           X-Ray   Advanced protocol   2023-05-09    2097.48
95           X-Ray  Standard procedure   2023-07-07     812.41
96    Chemotherapy     Basic screening   2023-05-06    2835.77
97             ECG   Advanced protocol   2023-03-17     804.26
98             MRI     Basic screening   2023-07-04    4101.60
99   Physiotherapy   Advanced protocol   2023-03-02    1551.70
100            MRI  Standard procedure   2023-09-21    2930.05
101            MRI     Basic screening   2023-10-25    4460.36
102            ECG     Basic screening   2023-01-24    3428.95
103            ECG   Advanced protocol   2023-04-18    2898.31
104            ECG     Basic screening   2023-08-14    1959.50
105          X-Ray   Advanced protocol   2023-10-29    1998.51
106   Chemotherapy   Advanced protocol   2023-04-17    3512.69
107          X-Ray   Advanced protocol   2023-04-21    4973.63
108   Chemotherapy   Advanced protocol   2023-07-29    3478.28
109   Chemotherapy  Standard procedure   2023-07-19    3010.03
110            MRI   Advanced protocol   2023-05-22    3787.93
111            MRI     Basic screening   2023-01-11    2593.43
112   Chemotherapy  Standard procedure   2023-11-24     770.64
113   Chemotherapy     Basic screening   2023-08-08    3030.34
114          X-Ray  Standard procedure   2023-10-25    4809.31
115          X-Ray   Advanced protocol   2023-07-07    1288.86
116            MRI  Standard procedure   2023-06-20    3605.02
117            ECG  Standard procedure   2023-08-09    1404.20
118   Chemotherapy     Basic screening   2023-12-18    2911.22
119          X-Ray     Basic screening   2023-12-08     935.04
120            MRI   Advanced protocol   2023-04-07    2526.67
121          X-Ray  Standard procedure   2023-07-11    3902.73
122   Chemotherapy  Standard procedure   2023-02-28    2064.07
123   Chemotherapy  Standard procedure   2023-03-16    3492.10
124  Physiotherapy   Advanced protocol   2023-02-18    4079.52
125            ECG   Advanced protocol   2023-11-02    4672.30
126  Physiotherapy   Advanced protocol   2023-11-13    1555.89
127            MRI   Advanced protocol   2023-04-15    2296.92
128          X-Ray   Advanced protocol   2023-08-25    1185.87
129            MRI     Basic screening   2023-02-23    4966.18
130   Chemotherapy  Standard procedure   2023-05-11    4671.50
131  Physiotherapy  Standard procedure   2023-07-26    2929.81
132  Physiotherapy  Standard procedure   2023-03-23    4289.15
133  Physiotherapy  Standard procedure   2023-10-17    2844.31
134            MRI  Standard procedure   2023-09-09    3306.14
135   Chemotherapy  Standard procedure   2023-05-13     901.06
136          X-Ray  Standard procedure   2023-10-25    3898.72
137          X-Ray  Standard procedure   2023-12-26    1074.71
138            MRI     Basic screening   2023-10-10    4217.30
139  Physiotherapy  Standard procedure   2023-02-05    4019.13
140            ECG     Basic screening   2023-06-15    3689.35
141            MRI   Advanced protocol   2023-11-01     662.72
142            MRI  Standard procedure   2023-09-21    1864.08
143   Chemotherapy   Advanced protocol   2023-08-16    1684.01
144          X-Ray   Advanced protocol   2023-11-11    2120.61
145            MRI   Advanced protocol   2023-01-05     894.39
146            MRI     Basic screening   2023-11-13    4716.31
147  Physiotherapy   Advanced protocol   2023-12-06    2992.11
148  Physiotherapy   Advanced protocol   2023-07-26    1874.86
149            ECG   Advanced protocol   2023-08-16    2286.42
150   Chemotherapy  Standard procedure   2023-01-28    2512.41
151            ECG  Standard procedure   2023-04-14    3202.67
152  Physiotherapy     Basic screening   2023-07-08    2820.56
153          X-Ray     Basic screening   2023-03-06    4637.26
154  Physiotherapy  Standard procedure   2023-01-03    2736.34
155   Chemotherapy     Basic screening   2023-11-22    4964.71
156  Physiotherapy  Standard procedure   2023-05-12    4331.41
157   Chemotherapy   Advanced protocol   2023-07-12    1438.30
158   Chemotherapy   Advanced protocol   2023-04-08    4687.68
159   Chemotherapy     Basic screening   2023-12-17    1023.65
160   Chemotherapy  Standard procedure   2023-06-17    4178.52
161   Chemotherapy  Standard procedure   2023-01-01    2212.80
162          X-Ray     Basic screening   2023-06-27    4450.88
163            ECG  Standard procedure   2023-07-28    4406.26
164            MRI   Advanced protocol   2023-04-04    4126.66
165            ECG     Basic screening   2023-01-12    4055.14
166   Chemotherapy     Basic screening   2023-11-15    1871.06
167          X-Ray  Standard procedure   2023-09-29     864.14
168  Physiotherapy     Basic screening   2023-07-24    2313.41
169          X-Ray  Standard procedure   2023-03-03    1280.86
170   Chemotherapy  Standard procedure   2023-04-18    3627.28
171          X-Ray  Standard procedure   2023-03-09    2057.45
172          X-Ray  Standard procedure   2023-06-04    4890.25
173   Chemotherapy  Standard procedure   2023-10-31    3384.37
174          X-Ray     Basic screening   2023-10-22    4201.16
175            MRI   Advanced protocol   2023-04-26    1096.36
176            MRI   Advanced protocol   2023-08-16    4379.07
177          X-Ray     Basic screening   2023-01-17    4652.41
178  Physiotherapy     Basic screening   2023-03-08    2691.78
179   Chemotherapy   Advanced protocol   2023-01-07    3228.14
180            MRI   Advanced protocol   2023-09-03    3941.64
181  Physiotherapy   Advanced protocol   2023-04-12    1286.77
182          X-Ray   Advanced protocol   2023-02-03    2761.55
183  Physiotherapy   Advanced protocol   2023-02-26    2293.98
184            ECG  Standard procedure   2023-03-21    1158.68
185            MRI     Basic screening   2023-03-27    2153.90
186          X-Ray  Standard procedure   2023-02-13     806.78
187   Chemotherapy   Advanced protocol   2023-04-12     616.15
188          X-Ray   Advanced protocol   2023-10-05    1108.25
189   Chemotherapy   Advanced protocol   2023-11-16    4834.02
190          X-Ray  Standard procedure   2023-04-12    2972.88
191  Physiotherapy  Standard procedure   2023-08-31    4846.20
192  Physiotherapy   Advanced protocol   2023-09-15    2446.24
193  Physiotherapy  Standard procedure   2023-04-06    1903.17
194            ECG  Standard procedure   2023-08-19    2777.64
195   Chemotherapy   Advanced protocol   2023-10-26    2477.80
196  Physiotherapy  Standard procedure   2023-04-01     975.49
197            ECG     Basic screening   2023-05-15    3383.72
198   Chemotherapy     Basic screening   2023-05-01    1472.17
199          X-Ray     Basic screening   2023-12-30    3288.15

In [22]:
! pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.2.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.1.3)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.1.6)
Collecting importlib_resources>=1.2.0 (from sweetviz)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Downloading sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 74.0 MB/s  0:00:00
Downloading importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Installing collected packages: importlib_resources, sweetviz
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [sweetviz]
Successfully installed importlib_resources-7.1.0 sweetviz-2.3.3

In [23]:
import sweetviz as sv

report = sv.analyze(A)  # Appointments dataset
report.show_html("appointments_report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report appointments_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.